################################################################################
###                                                                          ###
### Created by Alexandre Daby-Seesaram                                       ###
###                                                                          ###
### Ã‰cole Polytechnique, Palaiseau, France                                   ###
###                                                                          ###
################################################################################


project:
  resources:
    # - "Template"
    - "Resources"
  type: website
  output-dir: public


format: 
  revealjs:
    css: Template/ENSTA.css
    smaller: true
    html-math-method: 
      method: mathjax
      url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js"
    slide-number: c/t
    show-slide-number: all
    code-fold: true
    theme: Template/ENSTA_template.scss
    logo: Template/E4H_ENSTA.svg
    date-format: long
    title-slide-attributes: 
        data-background-image: "Template/BG.svg"
jupyter: python3
execute:
  freeze: auto
progress: true
touch: true
controls: true
loadIcons: true
bibliography: ../Pres-2026.bib
csl: Template/apa.csl
